FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["BarberShopAPI/BarberShopAPI.csproj", "BarberShopAPI/"]
RUN dotnet restore "BarberShopAPI/BarberShopAPI.csproj"
COPY . .
WORKDIR "/src/BarberShopAPI"
RUN dotnet build "BarberShopAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BarberShopAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BarberShopAPI.dll"]
